### ISSUE TITLE
Raspberry Pi build issue

### ISSUE THREAD

**Issue by scottsweb** [PunchThrough/node-red-contrib-bean#10]
This might be related to #9 but I am not getting the permissions errors. Upgrading to the latest version I am seeing the following:

```
> usb@1.1.0 install /home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
compilation terminated.
libusb.target.mk:124: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.7-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding"
gyp ERR! cwd /home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb
gyp ERR! node -v v0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 4.1.7-v7+
node-pre-gyp ERR! command "node" "/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding' (1)
npm WARN optional dep failed, continuing usb@1.1.0

> bluetooth-hci-socket@0.4.2 install /home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make: Entering directory '/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o

SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/build'
node-red-contrib-bean@0.5.0 node_modules/node-red-contrib-bean
├── async@0.9.2
└── ble-bean@2.1.0 (noble-device@1.1.0, crc@2.1.1, noble@1.2.0)
```

Both issues seem to be stalling around the `usb` package. 

node-red is seeing the node but the status is a continuous loop (searching -> connecting -> connected), repeated every few seconds.

**Comment by scottsweb** [comment]
Checking the `node-red` logs I am also seeing:

```
at Peripheral.addListener (events.js:179:15)
    at NobleDevice (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble-device/lib/noble-device.js:18:20)
    at new Bean (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/lib/Bean.js:18:15)
    at Noble.constructor.onDiscover (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble-device/lib/util.js:28:22)
    at Noble.emit (events.js:107:17)
    at Noble.onDiscover (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/lib/noble.js:144:10)
    at emit (events.js:118:17)
    at NobleBindings.onDiscover (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/lib/hci-socket/bindings.js:155:10)
    at emit (events.js:118:17)
    at Gap.onHciLeAdvertisingReport (/home/scott/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/lib/hci-socket/gap.js:160:10)
```

**Comment by scottsweb** [comment]
Reported upstream too: https://github.com/nonolith/node-usb/issues/103

**Comment by scottsweb** [comment]
@raykamp do you have any suggestions on how I might get around this temporarily? I have tried to roll back to an earlier version of `node-red-contrib-bean` but it is still trying to use newer dependencies.

**Comment by scottsweb** [comment]
I have managed to build the `usb` package (the other ticket is now closed: https://github.com/nonolith/node-usb/issues/103) but unfortunately things are still not working correctly. I am currently seeing this in `node-red`:

![bean](https://cloud.githubusercontent.com/assets/411945/11168278/d48d40f2-8b7f-11e5-976b-dfedf793c079.gif)

Not sure what I can do to fix this. On the Mac using bean loader the connection is fine.

**Comment by aderhgawen** [comment]
@scottsweb Is there any timeout set for the Bean node? On my computer that happens only if I have a timeout set - 
![bean-node](https://cloud.githubusercontent.com/assets/7635230/11548771/0790f020-991d-11e5-9798-44f993a2fc22.png)

**Comment by scottsweb** [comment]
@aderhgawen afraid not. I am constantly connected to the Bean (which is another problem I need to solve).

I did eventually get around this by upgrading my Raspberry Pi from Wheezy to Jessie. Everything then built as expected.

**Comment by scottsweb** [comment]
Happy to close this now. Everything is OK on Jessie.
