### ISSUE TITLE
Problem installing on rpi

### ISSUE THREAD

**Issue by devth** [PunchThrough/node-red-contrib-bean#9]
Seeing lots of errors when I install on a raspberry pi:

```
pi@raspberrypi ~/.node-red $ npm install --prefix ~/.node-red node-red-contrib-bean
npm http GET https://registry.npmjs.org/node-red-contrib-bean
npm http 304 https://registry.npmjs.org/node-red-contrib-bean
npm ERR! error rolling back Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp'
npm ERR! error rolling back  node-red-contrib-bean@0.5.0 { [Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp' }
npm ERR! Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp'
npm ERR!  { [Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.1.7+
npm ERR! command "/home/pi/.nvm/v0.10.17/bin/node" "/home/pi/.nvm/v0.10.17/bin/npm" "install" "--prefix" "/home/pi/.node-red" "node-red-contrib-bean"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v0.10.17
npm ERR! npm -v 1.3.8
npm ERR! path /home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi ~/.node-red $ rm -rf node_modules/
rm: cannot remove `node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/node_modules/.bin/rimraf': Permission denied
rm: cannot remove `node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/node_modules/.bin/mkdirp': Permission denied
rm: cannot remove `node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/node_modules/.bin/rc': Permission denied
rm: cannot remove `node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/node_modules/.bin/semver': Permission denied
rm: cannot remove `node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/node_modules/.bin/nopt': Permission denied
rm: cannot remove `node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp': Permission denied
pi@raspberrypi ~/.node-red $ sudo rm -rf node_modules/
pi@raspberrypi ~/.node-red $ npm install --prefix ~/.node-red node-red-contrib-bean
npm http GET https://registry.npmjs.org/node-red-contrib-bean
npm http 304 https://registry.npmjs.org/node-red-contrib-bean
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/crc
npm http GET https://registry.npmjs.org/noble
npm http GET https://registry.npmjs.org/noble-device
npm http 304 https://registry.npmjs.org/crc
npm http 200 https://registry.npmjs.org/noble-device
npm http 200 https://registry.npmjs.org/noble
npm http GET https://registry.npmjs.org/xpc-connection
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/bluetooth-hci-socket
npm http GET https://registry.npmjs.org/bplist-parser/0.0.6
npm http 200 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/bplist-parser/0.0.6
npm http 304 https://registry.npmjs.org/bluetooth-hci-socket
npm http 304 https://registry.npmjs.org/xpc-connection
npm WARN optional dep failed, continuing xpc-connection@0.1.4
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/usb
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 200 https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/usb
npm http 200 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> usb@1.0.6 install /home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://tessel-builds.s3-us-west-2.amazonaws.com/pre-gyp/usb/v1.0.6/usb_bindings-v1.0.6-node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://tessel-builds.s3-us-west-2.amazonaws.com/pre-gyp/usb/v1.0.6/usb_bindings-v1.0.6-node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://tessel-builds.s3-us-west-2.amazonaws.com/pre-gyp/usb/v1.0.6/usb_bindings-v1.0.6-node-v11-linux-arm.tar.gz (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
../libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
compilation terminated.
libusb.target.mk:120: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/v0.10.17/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 4.1.7+
gyp ERR! command "/home/pi/.nvm/v0.10.17/bin/node" "/home/pi/.nvm/v0.10.17/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/pi/.nvm/v0.10.17/bin/node /home/pi/.nvm/v0.10.17/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 4.1.7+
node-pre-gyp ERR! command "node" "/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb
node-pre-gyp ERR! node -v v0.10.17
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute '/home/pi/.nvm/v0.10.17/bin/node /home/pi/.nvm/v0.10.17/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/node_modules/usb/src/binding' (1)
npm WARN optional dep failed, continuing usb@1.0.6

> bluetooth-hci-socket@0.4.0 install /home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-bean/node_modules/ble-bean/node_modules/noble/node_modules/bluetooth-hci-socket/build'
node-red-contrib-bean@0.5.0 node_modules/node-red-contrib-bean
├── async@0.9.2
└── ble-bean@2.1.0 (noble-device@1.1.0, crc@2.1.1, noble@1.2.0)
```

After install I restarted node-red but it still just hangs on "searching..". Any ideas?

**Comment by aderhgawen** [comment]
I see many "permission denied" errors. Have you tried running the commands with "sudo"?
